### PR TITLE
Fixup/delete by id/key fixup

### PR DESCRIPTION
**Pull request by AltesHaus**
Tested it, everything runs smoothly. 
Just rebase (commit-fixups) needed

### CODE REVIEW

**Review by TELBC — APPROVED** [review]
lgtm

**Review by NicoJanis — CHANGES_REQUESTED** [review]
Same as other pull request we cannot just remove the private key - large class discussion

**Comment by BenjaminSobhian** [comment]
we need to think about private/public keys and if we need both

**Comment by XenoxJeager** [comment]
you cannot just remove the private keys , using my string key stuff as a key is highly ineffective. Please what are your reasons to just remove the private keys?

**Review by NicoJanis — CHANGES_REQUESTED** [review]
Please change back to old id and only request the other changes

**Pull request closed without merging**
